#!/usr/bin/env php
<?php

// Fill given shopping basket. You must supply session cookie

require_once __DIR__ . '/scraper.php';

class WifiStockShopper {

    function __construct($cookie) {
        // Fetch HTML with cURL
        $this->ch = curl_init();
        curl_setopt_array($this->ch, [
            CURLOPT_URL => 'https://www.wifi-stock.com/index.php?ajax=cart',
            CURLOPT_COOKIE => "PHPSESSID=".$cookie,
            CURLOPT_FOLLOWLOCATION => 1,
            CURLOPT_MAXREDIRS => 5,
            CURLOPT_RETURNTRANSFER => 1,
        ]);

        $html = curl_exec($this->ch);
        $this->balance = $this->parseBalance($html);
    }

    function parseBalance($html) {
        $scraper = new Scraper($html);
        return $scraper->scrape([
            "xpath" => '//span[@class="total"]',
            "regex" => '/^\s*([0-9.]+)/',
            "group" => 1,
        ]);
    }

    function addProduct($code, $qty) {
        curl_setopt($this->ch, CURLOPT_POSTFIELDS, [
            "id" => $code,
            "qty" => $qty,
        ]);
        
        $html = curl_exec($this->ch);
        $new_balance = $this->parseBalance($html);
        $ret = $this->balance !== $new_balance;
        $this->balance = $new_balance;
        return $ret;
    }
}

if (count($argv) !== 2) {
    fprintf(STDERR, "Usage: %s WIFISTOCK_PHPSESSID_COOKIE\n", $argv[0]);
    exit(1);
}

$shop = new WifiStockShopper($argv[1]);

print("Start amount: {$shop->balance}\n");

while (FALSE !== ($line = fgetcsv(STDIN, 0, "\t"))) {
    $ok = $shop->addProduct($line[1], $line[0]);
    if (!$ok) {
        print("Unable to add product $line[1]\n");
    }
}

print("Final amount: {$shop->balance}\n");
